// <auto-generated />
using System;
using ArgosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArgosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710223755_AdicionaDescricaoNoProjeto")]
    partial class AdicionaDescricaoNoProjeto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArgosApi.Domain.Entities.Projeto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_projeto");

                    b.ToTable("projeto", (string)null);
                });

            modelBuilder.Entity("ArgosApi.Domain.Entities.Relatorio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHoraExecucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_execucao");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("integer")
                        .HasColumnName("pontuacao");

                    b.Property<long>("ProjetoId")
                        .HasColumnType("bigint")
                        .HasColumnName("projeto_id");

                    b.Property<int>("QuantidadeAvisos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_avisos");

                    b.Property<int>("QuantidadeErros")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_erros");

                    b.Property<bool>("TradutorLibrasIdentificado")
                        .HasColumnType("boolean")
                        .HasColumnName("tradutor_libras_identificado");

                    b.HasKey("Id")
                        .HasName("pk_relatorio");

                    b.HasIndex("ProjetoId")
                        .HasDatabaseName("ix_relatorio_projeto_id");

                    b.ToTable("relatorio", (string)null);
                });

            modelBuilder.Entity("ArgosApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("ProjetoUsuario", b =>
                {
                    b.Property<long>("ProjetosId")
                        .HasColumnType("bigint")
                        .HasColumnName("projetos_id");

                    b.Property<long>("UsuariosId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuarios_id");

                    b.HasKey("ProjetosId", "UsuariosId")
                        .HasName("pk_projeto_usuario");

                    b.HasIndex("UsuariosId")
                        .HasDatabaseName("ix_projeto_usuario_usuarios_id");

                    b.ToTable("projeto_usuario", (string)null);
                });

            modelBuilder.Entity("ArgosApi.Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("ArgosApi.Domain.Entities.Projeto", "Projeto")
                        .WithMany("Relatorios")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relatorio_projeto_projeto_id");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("ProjetoUsuario", b =>
                {
                    b.HasOne("ArgosApi.Domain.Entities.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projeto_usuario_projetos_projetos_id");

                    b.HasOne("ArgosApi.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projeto_usuario_usuarios_usuarios_id");
                });

            modelBuilder.Entity("ArgosApi.Domain.Entities.Projeto", b =>
                {
                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
